name: Only accept pulling request into staging branch via specific user

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    branches:
      - 'staging'
      - 'release/OAM-[0-9]+'
    types: [opened, reopened]

jobs:
  accept-pr-staging-control:
    runs-on: ubuntu-latest
    env:
      # Define allowed users as a comma-delimited string with commas at both ends for exact matching.
      ALLOWED_USERS: ",phtrung212,"
      ORG: "phtrungorg"
      TEAM_SLUG: "vn-team"
    steps:
      - name: Check PR conditions and exit early if applicable
        run: |
          echo "Starting PR checks..."
          # Check event type
          EVENT_TYPE="${{ github.event.action }}"
          if [ "$EVENT_TYPE" == "synchronize" ]; then
            echo "PR event is synchronize. Exiting early."
            exit 0
          fi

          # Get the PR author
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          echo "PR author: $PR_AUTHOR"
          
          # If the author is in the allowed list, exit early
          if [[ "$ALLOWED_USERS" == *",$PR_AUTHOR,"* ]]; then
            echo "User $PR_AUTHOR is in the allowed list. Exiting early."
            exit 0
          fi

          # Check if the author is a member of the GogoJungle Vietnam team
          echo "Checking team membership for user $PR_AUTHOR in team ${TEAM_SLUG}..."
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.ORG_TOKEN }}" \
            "https://api.github.com/orgs/${ORG}/teams/${TEAM_SLUG}/memberships/${PR_AUTHOR}")
          echo "Team membership API response: $response"
          
          # If the user is not a member of the team, no further check is needed.
          if [ "$response" -ne 200 ]; then
            echo "User $PR_AUTHOR is not a member of the team. Exiting early."
            exit 0
          fi

          # At this point, the user is a member of the team but not in the allowed list.
          echo "User $PR_AUTHOR is in the team but not allowed to create PRs to staging."
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMENT_BODY="Closed: User @${PR_AUTHOR} (member of GogoJungle Vietnam) is not authorized to create pull requests to the staging branch."
          
          echo "Adding comment to PR #${PR_NUMBER}..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
            -d "{\"body\": \"${COMMENT_BODY}\"}"
          
          echo "Closing PR #${PR_NUMBER}..."
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
            -d '{"state": "closed"}'
          
          # Exit with a non-zero code to mark the check as failed.
          exit 1
